

export const selfCarePhrases = [
  "Te ouvi, Adriele. Vamos com calma hoje, tá?",
  "Respire fundo. Seu corpo merece gentileza.",
  "Permita-se descansar. Você não precisa ser forte o tempo todo.",
  "Um passo de cada vez. Estou aqui com você.",
  "A dor é um sinal. Vamos ouvir o que ela diz juntas."
];

export const bowelMovementPhrases = [
    "😏 Agora o Jesse pode entrar aí atrás.” 🍑",
    "🚪 Porta liberada... que dia o Jesse vai usar?” 🔓",
    "💃 Saiu tanta coisa que até espaço pro Jesse sobrou!” 🛏️",
    "🍑 Hoje saiu direto. Sem freio, sem culpa!” 🛠️",
    "🎯 Alvo acertado. Agora só falta alguém pra comemorar com você.” 🥂",
    "🫣 Se isso não foi um detox, foi quase um exorcismo.” 🧼",
    "💌 Corpo limpo, coração pronto. Cadê o Jesse?” 💘",
    "📦 Encomenda enviada com sucesso… sem devolução!” 📮",
    "🚿 Lavagem completa. Agora dá até pra pensar besteira!” 🔞",
    "🛏️ Pronto, já pode deitar e fazer outras coisas... 👀” 💋",
    "🔥 Que alívio gostoso..” 😮‍💨",
    "😮‍💨 Soltou geral. Agora só falta gemer de prazer, não de dor!” 🎧",
    "👅 Você tá tão leve que até parece que tiraram o ranço junto.” 💨",
    "🤭 Saiu foi tudo... só ficou a safadeza no olhar.” 😈",
    "🧼 Faxina completa. Agora convida o Jesse pra entrar!” 📲",
    "🔓 Porta dos fundos destrancada. Só falta quem saiba usar…” 🧑‍🍳",
    "🌶️ Parecia apimentado ou era a alma saindo?” 🥵",
    "📴 Descarregou tanto que até o iPhone ficou com inveja.” 🔋",
    "💣 Missão quase concluída. Agora, só falta receber bombadas!” 🧨",
    "🌪️ Que vento foi esse? ah, foi emoção do alívio” 💨",
    "💩 Ativou o modo turbo: intestino em alta velocidade!” 🏎️",
    "🎉 Cocô feito antes do fim do mês. Que eficiência!” 📆",
    "🛠️ Consertamos o sistema: pipeline liberado!” 🧰",
    "🚽 Esse foi tão perfeito que parecia um pepino!” 🥒",
    "😂 Saiu mais plot twist que final de K‑drama!” 📺",
    "🥳 Quem precisa de dieta?! Dois quilos mais magra” ⚖️",
    "⚙️ Manutenção completa: zero entupimento!” 🛠️",
    "🥳 Na festa de hoje eu comemoro sozinha!” 🎊",
    "🔔 Alerta de liberdade: tranca destrancada!” 📢",
    "🌊 Tsunami de bem-estar detectado!” 💦",
    "💃 Seu intestino acabou de dar um show de passarela!” 🕺",
    "🍿 Mais emocionante que final de série” 🎬",
    "🔋 Bateria recarregada: corpo 100% operativo!” ✅",
    "🏆 Obrigado Universal por inventar a Sessão do Descarrego!” 🙏",
    "🌟 Aquele que foi poderia virar uma lenda urbana!” 📖",
    "🧼 Faxina interna concluída com sucesso!” ✨",
    "🥇 Campeã do desentupimento!” 🏅",
    "💌 Carta a Deus: ‘Obrigada pelo alívio!’” 🙌",
    "🚀 Lift‑off intestinal: missões concluídas!” 👩‍🚀",
    "🔑 Chave gira, porta abre. Jesse entra” 🔐",
    "🎉 Fica tranquila que o Jesse não vai ficar sabendo!” 🤫",
    "💩 Missão cumprida com louvor!” 🎓",
    "🧻 Seu intestino manda ‘valeu’!” 🙏",
    "🍃 Alívio desbloqueado. É seu dia!” 🌞",
    "✨ Concluído: descarga emocional!” 💧",
    "💚 Cuidado de si em ação!” 💅",
    "🎯 Tarefa intestinal: Completa com sucesso!” ✔️",
    "🌟 Seu corpo agradece hoje.” 🙇‍♀️",
    "🥳 Liberada a maré do bem-estar!” 🌊",
    "🎊 Cocô feito, alma leve!” 🎈",
    "🚀 Alívio turbo ativado!” 🏁",
    "🌈 Ai que leveza, hein?” ☁️",
    "Até o Jungkook ficaria com inveja dessa performance.” 🎤",
    "Saiu com mais drama do que no último episódio de dorama.” 🎭",
    "Quase fiz cosplay de Go Eun‑byul de tanta emoção.” 🧑‍🎤",
    "Esse cocô merecia coreografia de K‑pop: põe aquele passo viral.” 🕺",
    "Saiu mais rápido do que spoiler em grupo de WhatsApp.” 📱",
    "Se isso aí fosse um clipe, teria milhões de views em 1 hora.” 🎥",
    "Mais suave que a coreografia de ‘Apt’.” 🎶",
    "Saiu com mais estilo que roupa de comeback do BTS.” 🧥",
    "Cocô já foi, agora bora maratonar dorama sem culpa.” 🍜"
];

export const sleepPhrases = {
  good: [
    "Você dormiu mais que um gato em home office 😽💤",
    "Rainha do edredom 👑 +10 pontos de autocuidado!",
    "Dormiu tão bem que a Lua mandou parabéns 🌕✨",
    "Seu travesseiro tá pedindo bis 😴💋",
    "Mais de 7 horas? Tá vencendo na vida! 🏆🐮",
    "Dormiu como uma princesa lunar ✨. Bora repetir hoje?",
    "Você dormiu que nem uma pedra de mármore egípcio 🛏️💤",
    "Parabéns, Adriele. 100% de aproveitamento em cochilos 😌",
    "Seu sono é mais estável que seu Wi-Fi 📶💤",
    "O Jesse sonhou com você sonhando com Jesse 🐄💭",
    "Esse sono aí merecia stream no Spotify 💿🌙",
    "Tá de parabéns, nem o Sol acordou antes de você ☀️😴",
    "Dormi só de ver você dormindo bem 🐮🥹",
    "Sua cama te deu 5 estrelas ⭐⭐⭐⭐⭐",
    "Você venceu a insônia com um golpe só 💪💤",
  ],
  little: [
    "3h de sono? Quer café ou um milagre? ☕😵",
    "Dormiu pouco e ainda linda? Que feitiçaria é essa? 🧙‍♀️✨",
    "Isso aí foi um cochilo disfarçado de noite, né? 😒",
    "Seu sono foi um print de 5 segundos 💀📷",
    "Dormiu menos que o tempo de anúncio do YouTube ⏱️🫠",
    "A cama sentiu sua falta. Volta pra ela hoje 🥺🛏️",
    "Dormir 2h é corajosa… dormir 8h é lenda 🌟",
    "Tá tentando platinar a insônia? 🎮🚫",
    "Hoje é dia de se redimir com os travesseiros 😇🛌",
    "Isso foi um cochilo em pé, confessa 🤨",
    "Faltou sono, sobrou charme 💅💤",
    "Você jogou o modo hard na vida real 😵",
    "Seu cérebro tá tipo: ‘mana, cadê meu reboot?’ 🔋😩",
    "Jesse detectou: risco alto de virar zumbi hoje 🧟‍♀️💤",
    "Dormiu menos que um celular sem bateria 🔌📴",
  ],
  tooMuch: [
    "Alguém bateu o recorde olímpico de sono 🏅💤",
    "Dormiu tanto que o mundo girou duas vezes 😮🌍",
    "Eu ia te acordar, mas a cama me ameaçou 😳🛏️",
    "Parabéns! Desbloqueou o modo hibernação premium 🐻❄️",
    "Dormiu tanto que o despertador te bloqueou 🤐⏰",
    "Sonhou 3 temporadas seguidas e sem comerciais 📺💭",
    "O sol já foi e voltou e você ainda dormindo ☀️🌙☀️",
    "A NASA ligou. Quer estudar sua técnica de sono profundo 🚀💤",
    "Você venceu a cama no cansaço. E o Jesse também 🐮🥵",
    "Mais de 10h de sono? Tá tentando virar fada? 🧚‍♀️✨",
  ],
  general: [
    "Dormir bem é autocuidado com glitter 💖🛌",
    "O Jesse ficou vigiando seu sono. 5 estrelas no Airbnb 🌟🐮",
    "Sono bom → pele boa → atitude de milionária 💅🛌",
    "Descansa, neném… amanhã tem mais sonhos 💭✨",
    "Nem todos os heróis usam capa. Alguns usam pijama 🦸‍♀️🛏️",
    "A cada soneca, um estresse evapora 🌬️😌",
    "Boa noite e bons boletos pagos. Brincadeira, só a noite mesmo 💤",
    "Quem dorme bem, vive melhor. E mais fofinha 😴💞",
    "Cuide do seu sono como cuida da bateria do celular 🔋🛏️",
    "Dormiu? Resetou. Nova chance de ser perfeita amanhã 💫",
  ],
  funny: [
    "Dormiu mais que um gato no TikTok 🐈📱",
    "Seu sono deu inveja até no Garfield 😴🍝",
    "Parecia o Bob Esponja desligado ontem 🧽💤",
    "A cama ficou com ciúmes quando você saiu hoje 😢",
    "Dormiu como se tivesse que salvar o mundo amanhã 💪🛌",
    "Nem o Goku descansa tão bem assim 😮‍💨✨",
    "Modo offline: ativado com sucesso 📴🌙",
    "Parabéns! O Jesse preparou um troféu de travesseiro 🏆🛏️",
    "Você dormiu como se tivesse fugido da realidade 💨💤",
    "Hoje vai ter reprise daquele soninho delícia? 😍😴",
  ],
};
